#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-therubyracer
Version  : 0.12.2
Release  : 6
URL      : https://rubygems.org/downloads/therubyracer-0.12.2.gem
Source0  : https://rubygems.org/downloads/therubyracer-0.12.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-therubyracer-lib
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-libv8
BuildRequires : rubygem-libv8-dev
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-ref
BuildRequires : rubygem-rspec-core

%description
# therubyracer
[![Gem Version](https://badge.fury.io/rb/therubyracer.png)](http://badge.fury.io/rb/therubyracer)
[![Build Status](https://travis-ci.org/cowboyd/therubyracer.png?branch=master)](https://travis-ci.org/cowboyd/therubyracer)
[![Dependency Status](https://gemnasium.com/cowboyd/therubyracer.png)](https://gemnasium.com/cowboyd/therubyracer)

%package lib
Summary: lib components for the rubygem-therubyracer package.
Group: Libraries

%description lib
lib components for the rubygem-therubyracer package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n therubyracer-0.12.2
gem spec %{SOURCE0} -l --ruby > rubygem-therubyracer.gemspec

%build
gem build rubygem-therubyracer.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
therubyracer-0.12.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/therubyracer-0.12.2.gem
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/therubyracer-0.12.2/gem.build_complete
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/therubyracer-0.12.2/gem_make.out
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/therubyracer-0.12.2/mkmf.log
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/Changelog.md
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/benchmarks.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/.RUBYARCHDIR.-.v8.time
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/accessor.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/accessor.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/array.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/array.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/backref.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/backref.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/constants.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/constants.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/constraints.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/constraints.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/context.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/context.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/date.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/date.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/exception.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/exception.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/external.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/external.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/function.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/function.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/gc.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/gc.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/handles.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/handles.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/heap.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/heap.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/init.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/init.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/invocation.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/invocation.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/locker.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/locker.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/message.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/message.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/object.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/object.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/primitive.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/primitive.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/rr.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/rr.h
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/rr.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/script.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/script.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/signature.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/signature.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/stack.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/stack.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/string.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/string.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/template.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/template.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/trycatch.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/trycatch.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/v8.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/v8.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/value.cc
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/value.o
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/therubyracer.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/access.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/access/indices.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/access/invocation.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/access/names.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/context.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/class.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/code.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/fixnum.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/fundamental.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/indentity.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/method.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/primitive.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/proc.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/reference.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/conversion/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/function.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/stack.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/weak.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/array_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/constants_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/exception_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/external_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/function_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/handles_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/locker_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/object_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/script_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/template_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/c/trycatch_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/mem/blunt_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/redjs_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/threading_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/v8/context_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/v8/conversion_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/v8/error_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/v8/function_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/spec/v8/object_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/thefrontside.png
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/therubyracer.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/therubyracer-0.12.2.gemspec

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/therubyracer-0.12.2/v8/init.so
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext/v8/init.so
/usr/lib64/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib/v8/init.so
